site_name: Documentation CUB Édimbourg
site_url: https://enzo-5.github.io/edimbourg/
copyright: Licence CC 4.0 FR BY-NC-SA - 2025 Agence CUB Édimbourg 

theme:
  name: material
  logo: ./media/logo.png  
  favicon: ./media/favicon.png 
  language: fr
  features:
    - navigation.footer
    - content.code.copy
  palette:
    primary: orange
    accent: orange

nav:
  - Accueil: index.md
  - CUB Édimbourg:
      - Documentations:
          - Introduction: docs/documentation/introduction.md
          - Cybersécurité:
              - Situation n°1 - Cyber: docs/documentation/Cybersécurité/Situation n°1 Cyber.md
              - Situation n°2 - Cyber: docs/documentation/Cybersécurité/Situation n°2 Cyber.md
              - Situation n°3 - Cyber: docs/documentation/Cybersécurité/Situation n°3 Cyber.md
              - Situation n°4 - Cyber: docs/documentation/Cybersécurité/Situation n°4 Cyber.md
              - Situation n°5 - Cyber: docs/documentation/Cybersécurité/Situation n°5 Cyber.md
              - Situation n°6 - Cyber: docs/documentation/Cybersécurité/Situation n°6 Cyber.md
          - DNS:
              - DNS Autorité: docs/documentation/DNS/CUB - Serveur DNS Autorité.md
              - DNS Récursif: docs/documentation/DNS/CUB - Serveur DNS Recursif.md
              - DNS1 Récursif: docs/documentation/DNS/CUB - Serveur DNS1 Récursif.md
              - DNS1 Esclave: docs/documentation/DNS/CUB - Serveur DNS1 esclave.md
          - Situations:
              - Situation n°0 - Plan: docs/documentation/Situations/Situation n°0 CUB – Plan d'adressage, Schéma logique & physique, Table de routage, NAT.md
              - Situation n°1 - CUB: docs/documentation/Situations/Situation n°1 CUB.md
              - Situation n°2 - CUB: docs/documentation/Situations/Situation n°2 CUB.md
              - Situation n°3 - CUB: docs/documentation/Situations/Situation n°3 CUB.md
              - Situation n°4 - CUB: docs/documentation/Situations/Situation n°4 CUB.md
              - Situation n°5 - CUB: docs/documentation/Situations/Situation n°5 CUB.md
              - Situation n°6 - CUB: docs/documentation/Situations/Situation n°6 CUB.md
          - Configurations:
              - Switch 3: docs/documentation/Configurations/Commutateur de configuration 3.md
              - Switch 2: docs/documentation/Configurations/Config Switch 2.md

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
